### ISSUE TITLE
How to get or generate the missing files in android studio

### ISSUE THREAD

**Issue by johnx32** [meganz/MEGAchat#530]
Hi guys
I want to know how to obtain or generate some files that do not appear when cloning the project Android (due to the .gitignore) 
https://github.com/meganz/android

the files are from the MegaChat project but it does not tell me how to generate it either,
help please without that I can not compile the android project
there are the files but in c ++ (.h .cpp) but I do not know how to use them or transform them into .java

MegaChatApi.java
MegaChatError.java
MegaChatRequest.java
MegaContactRequest.java
MegaEvent.java
MegaAccountSession.java
MegaChatCall.java
MegaChatError.java
MegaChatMessage.java
MegaChatRequest.java
MegaChatRoom.java
MegaHandleList.java
CameraSyncService.java
MegaUserAlert.java
MegaContactRequest.java
etc

**Comment by sergiohs84** [comment]
All those files are automatically generated by SWIG. They represent the bindings that enables the app and the MEGAchat's SDK to talk (C++ <--> Java).
You probably need to run the following script from our Android repository in order to generate the bindings: `android/app/src/main/jni/build.sh all`

**Comment by sergiohs84** [comment]
Closing this ticket. It will be tracked in the Android's ticket (https://github.com/meganz/android/issues/63)
