### ISSUE TITLE
to create a shell script to install prerequisites mention in readme.md

### ISSUE THREAD

**Issue by rpotter12** [meganz/MEGAchat#537]
I am new in this project. While reading readme.md I saw that we have to install some following packages in the system. 

![screenshot from 2018-12-30 22-52-43](https://user-images.githubusercontent.com/34352567/50549670-f958ad00-0c86-11e9-8133-09d0d30d3c77.png)

I am creating this issue to give a proposal for a feature request:- to create a shell script which will install all the packages just by running the script in the terminal.

**Comment by sergiohs84** [comment]
Thanks for your collaboration, Rohit
