### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by rpotter12** [meganz/MEGAchat#541]
as requirements.sh file is added in the repository (PR: #538 ) we should update the readme.md so that we can tell the users how to use this script.

**Comment by sergiohs84** [comment]
Hi @rpotter12 
We appreciate your collaboration and suggestions, and agree with you the new script should be mentioned in the Readme.md. However, that script is only for Debian, Ubuntu and similar distributions (ie. Fedora uses a different package system and the script will do nothing but throw errors). Furthermore, we assume that any developer knows how to satisfy those dependencies by installing the listed packages in his/her system. In consequence, we don't plan to maintain that script but, if you want to prepare a new PR explaining the usage and the limitations, it's welcomed.
Thanks

**Comment by rpotter12** [comment]
Hi @sergiohs84 
please let the issue be open.

When I started working on an open source I usually try to execute the project myself and if I don't understand the project then I look on the issue section. Sometimes it is difficult for new people on open source to understand the project. They usually prefer these same steps (1) try to execute by themselves (2) check issue section. 
So, I have a suggestion to open an issue before started working on something, so that we can discuss working on something is good or not. :)
