### ISSUE TITLE
Could we add acknowledge receipt on megachat ?

### ISSUE THREAD

**Issue by paul-p** [meganz/MEGAchat#772]
On my opinion the acknowledge of receipt is the only one important feature which is still missing in megachat to be used daily.

**Comment by sergiohs84** [comment]
Thank you Paul for your feedback. We used to provide that feature in the past. At that time, it was seen as an intromission in the user's privacy and, in consequence, we stopped to provide the acknowledge of reception for messages. Nevertheless, I will communicate your feedback. Perhaps we can add it as a user's option.
