### ISSUE TITLE
Videoconference performance

### ISSUE THREAD

**Issue by erotavlas-turbo** [meganz/MEGAchat#809]
Hi,
I’m currently testing different platform for videoconferencing. In particular, I’m comparing mega.nz, hangouts, teams, riot and jitsi. I cannot figure out what is the maximum number of users in a conference call (audio/video).
Thank you

**Comment by sergiohs84** [comment]
Currently, MEGAchat officially supports up to 20 participants in a call, all of them with audio. However, only 6 users would be able to join with video enabled (soft limit, you may manage to get 1 or 2 more under certain circumstances). The video, however, would be received by every participant in the call.
Said that, we might increase the number of participants in a near future.

**Comment by sergiohs84** [comment]
The aforementioned limits are specified here: https://github.com/meganz/MEGAchat/blob/612aac1b7178bf389231715b4d60fee91eaaf384/src/rtcModule/webrtc.h#L378

**Comment by erotavlas-turbo** [comment]
> The aforementioned limits are specified here:
> 
> https://github.com/meganz/MEGAchat/blob/612aac1b7178bf389231715b4d60fee91eaaf384/src/rtcModule/webrtc.h#L378
> 
> Should you want to try with more participants, you can adjust them to your needs and test. Feedback on that trial would be appreciated ;)

Thank you for your fast reply. I have one more question, is it possible to adjust the video quality?
